; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = ESP8266-based clock project with WiFi connectivity, NTP synchronization, and a touch-enabled TFT display.

[env:esp32-s3-devkitm-1]
framework = arduino
board_build.filesystem = littlefs
platform = espressif32 @ 6.6.0
board = esp32-s3-devkitm-1
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
monitor_speed = 115200
upload_speed = 406000
lib_deps = 
	tzapu/WiFiManager@^2.0.17
	bblanchon/ArduinoJson@^7.4.1
	arduino-libraries/NTPClient@^3.2.1
	mathertel/OneButton@^2.6.1
	bodmer/TFT_eSPI@^2.5.43
	https://github.com/kamilkrz/DigiFont.git#fix/remove-unused-variables
	https://github.com/kamilkrz/eSPI_Menu.git#fix/remove-compilation-warnings
	lennarthennigs/Button2@^2.4.1
build_flags = 
	-std=gnu++14
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DCORE_DEBUG_LEVEL=2
	-DCONFIG_FREERTOS_ASSERT_DISABLE=0
	-DCONFIG_FREERTOS_DEBUG_OCDAWARE=1
	-D ESPI_MENU_DEBUG_PRINT_DISABLED
	-D ESPI_MENU_MAX_ITEM_CHARS=25
	-D ESPI_MENU_MAX_STATUS_CHARS=30
	-D USER_SETUP_LOADED=1
	-D TOUCH_CS=-1
	-D ST7789_DRIVER=1
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=240
	-D TFT_MISO=-1
	-D TFT_MOSI=11
	-D TFT_SCLK=12
	-D TFT_CS=-1
	-D TFT_DC=7
	-D TFT_RST=6
	-D LOAD_GLCD=1
	-D LOAD_FONT2=1
	-D LOAD_FONT4=1
	-D SPI_FREQUENCY=27000000
	-D TFT_RGB_ORDER=TFT_GRB
	-D TFT_INVERSION_ON=1
build_unflags = 
	-std=gnu++11
